services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5001:5001"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - app-network
    command: sh -c "npx prisma migrate deploy && npx prisma generate && npm run dev"

  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
    networks:
      - app-network

volumes:
  postgres-data:

networks:
  app-network:
    driver: bridge
